iot_comm:
  ros__parameters:
    diagnostic_updater:
      period: 1.0
    use_sim_time: false
    run_frequency: 1.0
    mqtt_timeout: 60.0
    scraper_length: 2.0 # 刮板长度
    iface: enP4p65s0
    did: HZP155CP10003
    software_version: V1.0-20240123-123456
